### ISSUE TITLE
Memory<T>.UnsafePointer has overflow issues

### ISSUE THREAD

**Issue by mgravell** [davidfowl/Channels#104]
in `UnsafePointer`, if `_offset` is large and `SizeOf<T>` is not 1 (or if `_offset` is moderate if `SizeOf<T>` is large).

Presumably fixable by forcing `ulong`  multiplication?

**Comment by davidfowl** [comment]
Should be fixed by https://github.com/davidfowl/Channels/commit/a6c4f448800e522d13af983976e687970adfbdc3
