### ISSUE TITLE
Is this supposed to replace/include/be combined with the System.Threading.Tasks.Channels library currently on the .NET Core Labs repo?

### ISSUE THREAD

**Issue by i3arnon** [davidfowl/Channels#11]
Or is this library unrelated and just happens to be named the same?

I can see [System.Threading.Tasks.Channels](https://github.com/dotnet/corefxlab/blob/master/src/System.Threading.Tasks.Channels/README.md) shares much of the basic API and interfaces, but isn't exactly the same. and both implement different channels.

**Comment by davidfowl** [comment]
Not yet, these are IO specific channels. I've mentioned these to @stephentoub is passing but am fleshing them out a bit first.
