### ISSUE TITLE
Need to be able to tell if reading task is complete

### ISSUE THREAD

**Issue by moozzyk** [davidfowl/Channels#131]
If a channel stream is consumed externally there is no way to check if the stream has been closed for streaming. For instance if I pass the channel stream to a json reader and it throws I cannot tell if this is because the channel has been closed or something else happen. A workaround for now is to cast IChannel to Channel and get the Reading task (`if (((Channel)connection.Channel).Reading.IsCompleted)`)

**Comment by davidfowl** [comment]
Take a look at the master branch in sockets. It handles this.

**Comment by moozzyk** [comment]
Are you talking about this: https://github.com/davidfowl/Sockets/blob/master/samples/SocketsSample/EndPoints/JsonRpcEndpoint.cs#L49-L73? 

If so, I filed this issue because this pattern does not really work.

**Comment by davidfowl** [comment]
What doesn't work? What was there before was completely broken. If this doesn't work, then just call ReadAsync again.
