### ISSUE TITLE
IObseverable<> ISubject<>

### ISSUE THREAD

**Issue by grahamehorner** [davidfowl/Channels#137]
Idea channels abstraction could make use of IObservable<> ISubject<> IObserver<> from the Rx world to perform actions over streams of data and perform filter, buffering and transformation using linq.

**Comment by davidfowl** [comment]
Nope, IO<T> doesn't belong where T = byte, it would be horribly inefficient. IO<T> can build built on top of this low level library with de/serializers to transform data

**Comment by grahamehorner** [comment]
I was thinking more T = IQueryable<byte> or T = IChannel from the listener implementation which would be a hot/cold observerable ? something I used when doing a customer UDP service for collection of vehicle  telemetry from 10000s packets per second

**Comment by davidfowl** [comment]
The name channel is pretty bad (should be renamed), it's only bytes not T. It would be like using `IEnumerable<byte>` instead of using `Stream`.
