### ISSUE TITLE
Synchronous Write implementation

### ISSUE THREAD

**Issue by Yves57** [davidfowl/Channels#147]
Sorry to ask a question in a Github issue, but I don't know if there is another place to just ask questions about Channels.

Imagine I want to implement a synchronous method (for instance one of the synchronous `TextWriter` overrides).

I can write `_output.WriteAsync(myValue).GetAwaiter().GetResult()`, but:
- It is not the Channels spirit.
- I suppose it will be very slow to wait each time the task result.

Otherwise I can write in a temporary buffer (for example 1024 bytes), and calling `_output.WriteAsync(_myBuffer).GetAwaiter().GetResult()` only when the buffer is full.
- Less `WriteAsync()` calls.
- But buffer copy.

Or is there another solution?

**Comment by benaadams** [comment]
In channels Writing is sync; Flushing is async

**Comment by Yves57** [comment]
Not sure to understand. I agree that `WriteAsync` extension method calls a synchronous `Write` and then an asynchronous `FlushAsync`.

I will ask my question differently :-)

Suppose I write my class like this:

```
class MyBuggyTextWriter
{
   private WritableBuffer _buffer;

   private IWritableChannel _channel;

   public MyTextWriter(IWritableChannel channel)
   {
       _channel = channel;
       _buffer = _channel.Alloc();
   }

   public void Write1(string s)
   {
      _buffer.Write(....);
   }

   public void Flush()
   {
      _buffer.FlushAsync().GetAwaiter().GetResult();
   }

   public void Write2(string s)
   {
      _channel.WriteAsync(....).GetAwaiter().GetResult();
   }
}
```

If I use `Write1` and `FlushAsync`, the buffer will be flushed very late, it will grow and so the performances won't be optimal, no?
But if I use `Write2`, the asynchronous `FlushAsync` is always blocked, which is not better.

**Comment by benaadams** [comment]
Could flush behind?

``` csharp
class MyTextWriter
{
   private WritableBuffer _buffer;
   private Task _lastFlush = Task.CompletedTask;

   private IWritableChannel _channel;

   public MyTextWriter(IWritableChannel channel)
   {
       _channel = channel;
       _buffer = _channel.Alloc();
   }

   public void Write(string s)
   {
      _buffer.Write(....);
      _buffer.Commit();
   }

   public Task FlushAsync()
   {
      return _buffer.FlushAsync();
   }

   public void WriteAndFlush(string s)
   {
      Write(s);
      var flush = FlushAsync();
      _lastFlush.GetAwaiter().GetResult();
      _lastFlush = flush;
   }
}
```

**Comment by davidfowl** [comment]
sync writes either have to be buffered or blocking. The Task returned from FlushAsync will only be incomplete if there's some kind of back pressure (size limit). On top of that, the call to FlushAsync calls the consumer inline as everything is really blocking until the caller or consumers dispatches.

**Comment by Yves57** [comment]
@benaadams If I'm not wrong, the `Write` method could not be called several times because a buffer is freezed as soon as `Commit` has been called.

**Comment by Yves57** [comment]
So if I correctly understand, it is the user responsibility to choose between two solutions:

Solution 1: write in a buffer, and flush the buffer when it is full.
Pros:
- Less frequent calls to `FlushAsync` which is probably not totally free in term of performance.
- Less frequent calls to `FlushAsync` which can be sometimes blocking.

Cons:
- Managing the buffer filling.
- The consumer will be less "reactive", because it receives data only when the buffer is full.

Solution 2: write and flush in the same call (`WriteAsync(...).GetAwaiter().GetResult()`).
Pros and cons are exactly the mirrors of the previous solution.

**Comment by benaadams** [comment]
> If I'm not wrong, the Write method could not be called several times because a buffer is freezed as soon as Commit has been called.

Commit just moves the data to be available to be read by the reader; it doesn't release the buffer. Flush does that. However it also doesn't notify the reader that there is more data so it will only get picked up if there is a read in progress.

**Comment by Drawaes** [comment]
> If I'm not wrong, the Write method could not be called several times because a buffer is freezed as soon as Commit has been called.

Also you can call commit, and then do an ensure and commit again on the same buffer

buffer.Write();
buffer.Commit();
buffer.Ensure(sizeofwrite);
buffer.Write();
buffer.Commit();

any flush should show the consumer anything up to the last "commit"
