### ISSUE TITLE
Implement Encrypt and Decrypt Channel 

### ISSUE THREAD

**Issue by grahamehorner** [davidfowl/Channels#149]
Please consider a channel implementation that to encrypts/decrypts similar to compress/decompress

**Comment by Drawaes** [comment]
#128 it currently is in development! Although it might never make it in, unless I figure out ctrl K, D

**Comment by grahamehorner** [comment]
@Drawaes ?isn't #128 for secured connections SSL etc. I'm thinking encryption/decryption independent of the connection/transport protocol.

**Comment by Drawaes** [comment]
Can add it in to the tls library in the near future if it gets accepted.
OpenSSL provides raw crypto and I have been looking for an excuse to dig
into CNG

**Comment by grahamehorner** [comment]
@Drawaes there are a few requests on the corefx repo for public/private key crypto maybe the effort can be feedback into corefx ;)

**Comment by Drawaes** [comment]
Meh to the corefx report for now. If I make it and it works in channels and someone wants to back port they can have at it. So I have some questions for you. What ciphers are you thinking?
