### ISSUE TITLE
Unit tests?

### ISSUE THREAD

**Issue by ghost** [davidfowl/Channels#28]
Currently the sample project has `Console.ReadLine` at the end, which makes less like a suitable test app in CI scenario (for that matter both Travis and AppVeyor scripts are only `dotnet build`'ing the sample, not running it).

Even simulating `\n` key stroke from bash is not working for some reason on Unix:

``` sh
echo -ne '\n' | dotnet run -c Release -p samples/Channels.Samples
```

Having a xunit test project would make things better from continuous integration view point (and later merging upstream; to CoreFX).

**Comment by davidfowl** [comment]
Yea it's probably time to write some unit tests.

**Comment by davidfowl** [comment]
Added one!
