### ISSUE TITLE
UTF8 decoder is stateful - incorrectly held static

### ISSUE THREAD

**Issue by mgravell** [davidfowl/Channels#30]
`Decoder` is inherently stateful; pretty sure it isn't safe to be held as a `static Utf8Decoder` for use in `GetUtf8String`, as it will contain the state of the backlog of the bytes consumed that have not yet resulted in a char. Should probably do something like an interlocked swap with fallback of create new, so that it _usually_ manages to recycle.

Edit: you also shouldn't be flushing between segments, since you don't know that characters don't span spans (if you see what I mean).

**Comment by davidfowl** [comment]
Fixed by @mgravell 😄 https://github.com/davidfowl/Channels/commit/6813ca115a202869affcb9de6502f7f7499a291f

**Comment by mgravell** [comment]
Dammit, I meant to include `fix #30` in the commit message; my bad
