### ISSUE TITLE
Don't expose MemoryPoolBlock to consumers/producers of the channel

### ISSUE THREAD

**Issue by davidfowl** [davidfowl/Channels#4]

**Comment by TimLovellSmith** [comment]
+1 - memory pool block seems to be a poor way of expressing the current stated design goal "Channels invert the polarity of streams by flowing buffers up to user code. The user never allocates a buffer. All memory allocations are handled by the channel implementation itself. The idea is that the channel implementation can do the least amount of work to get data from a source and flow it to the caller so there's NEVER a copy. "

**Comment by davidfowl** [comment]
Done!
