### ISSUE TITLE
Request for ReadableBuffer.StartsWith method

### ISSUE THREAD

**Issue by mgravell** [davidfowl/Channels#41]
currently really awkward to do this - needs to consider single/multi-span etc, or use multiple `Slice` calls; will happily volunteer the code, but wanted to check I'm not missing a trick first

edit: I guess `StartsWith` is the same as a `Slice(0,len).Equals()`, if that existed

Similarly, in the area where I'm using this, I've had to do a lot of `.Slice(...).Slice(...)` because of the interplay of `ReadCursor` and `int` - which can't be added/subtracted. Would it be reasonable for `ReadCursor` to have `+`/`-` operators? or do they not have enough context to figure it out?

**Comment by benaadams** [comment]
> Similarly, in the area where I'm using this, I've had to do a lot of .Slice(...).Slice(...) because of the interplay of ReadCursor and int - which can't be added/subtracted. Would it be reasonable for ReadCursor to have +/- operators?

Is sort of rewindable? (for `-` )

Can skip forward with `Seek(n)` which returns how much it did go forward by (based on available data).

Can save current position by assigning the Cursor to another variable (struct clone)

So to check forward and rewind is sort of:

``` csharp
ReadCursor current;
...
var scanner = current;
if (scanner.Seek(1024) == 1024)
{
    // current is still at same position
}
```

**Comment by davidfowl** [comment]
Going back is hard just because the linked list doesn't store a back pointer. Then you'd also want `>` `<` operators which all make sense but would need to figure out an efficient way to implement those.

**Comment by mgravell** [comment]
Yeah, forget "back"; `Seek` looks encouraging, will have a look. Forget the second paragraph - it was late, I was tired. Any thoughts on the `StartsWith`? more than happy to throw something together...

**Comment by davidfowl** [comment]
Should it be an extension method or first class?

**Comment by mgravell** [comment]
almost certainly, but it isn't _actually_ text - although I guess it often will be used with text; I'm guessing `byte[], offset, count`.

**Comment by benaadams** [comment]
> Any thoughts on the StartsWith? 

Something with Vector.Equals :)

**Comment by mgravell** [comment]
Dude, you're obsessed! But, comparing 32 (or more on next gen CPUs) bytes
at a time sure is tempting...

**Comment by davidfowl** [comment]
Add it as a method on the struct then, we can always figure out where to move it in the long run.

**Comment by mgravell** [comment]
Implemented in https://github.com/davidfowl/Channels/pull/50 and merged
