### ISSUE TITLE
Support non-blocking I/O

### ISSUE THREAD

**Issue by roji** [davidfowl/Channels#48]
Just to make sure whether non-blocking I/O is going to be supported here.

Note that regular .NET Stream's Write() method returns void (unlike Linux's write system call, for example). Unless I'm mistaken this means it's effectively not possible to do non-blocking I/O unless you dump Stream and interact with the Socket directly.

**Comment by benaadams** [comment]
You should be using Stream's WriteAsync for non-blocking I/O

**Comment by roji** [comment]
@benaadams how is WriteAsync non-blocking I/O, as opposed to async? The two are very different things...

What I'm looking for is simple, classical non-blocking writes (setsockopt O_NONBLOCK). I'd like to be able to write only if that's possible without blocking - and for the call to return immediately in all cases. WriteAsync is a very a different thing - like other async operations, the continuation may run on another thread much later.

What's strange is that non-blocking _reads_ seems well-supported by Stream - you can set the socket to non-blocking and execute `Stream.Read()`, which would return immediately with the number of bytes read. I'm looking for the same thing with `Stream.Write()`.

**Comment by davidfowl** [comment]
This abstraction doesn't dictate how sockets are read. Just as stream cannot. That's an artifact of how the underlying system decides to write to or read from the the channel.

**Comment by roji** [comment]
I admit I haven't yet explored the channel API - all my comments are regarding the .NET Stream API.

The problem is that the Stream abstraction limits the types of I/O operations that may be represented. Note that `Stream.Read()` does return an int, allowing for less bytes to be read than was requested. In that sense `Stream.Read()` at the very least _supports_ non-blocking reads. The same is not true of `Stream.Write()`, which returns void, making it an unsuitable abstraction for non-blocking writes.

Non-blocking operations by definition do not block, and are therefore very different from async operations, which represent long-running operations which return Tasks. I think there's somewhat of a Windows/Unix divide here - in the (traditional) Unix world non-blocking I/O is used quite a lot, whereas Windows seems to have been more async-I/O oriented. This may have lead .NET to historically neglect non-blocking I/O somewhat. The two are very distinct I/O patterns, even if they sometimes can be used to achieve equivalent goals.

I hope I'm not missing something fundamental here.

**Comment by davidfowl** [comment]
That's all well and good but doesn't change my previous comment.

**Comment by roji** [comment]
@davidfowl can you provide more detail? In your comment your said that neither the channel nor the stream abstraction "dictate how sockets are read". But by returning void (rather than int), `Stream.Write()`, seems to "dictate" that non-blocking writes aren't supported.

**Comment by benaadams** [comment]
@roji not sure I understand? 

You want to do non-blocking writes to a socket; which has the exact method you are looking for on it:

``` csharp
int Send(byte[] buffer, int offset, int size ...)
```

What is a stream or channel abstraction adding in this circumstance? 

They can be layers on layers so if a write to a layering of `Text`->`GZip`->`Buffered`->`Ssl`->`Socket` doesn't complete everything, what does that mean? Is it because it would block on the socket, is it because there isn't enough data in the conversion steps to move the data to the next step etc

**Comment by roji** [comment]
@benaadams, that's a valid question.

First, note your comments are just as true for reading as they are for writing, and yet the `Stream.Read()` abstraction _does_ return an int, and may read less than what was requested. This asymmetry is odd and not really necessary.

Second, the fact that streams can be layered doesn't mean that non-blocking writes (or reads!) don't make sense. It's perfectly easy to imagine a `GzipStream` which knows how to handle cases where its underlying stream doesn't write as much as requested (because the operation would block), maintains internal state accordingly and bubbles that information up to the user; so if I ask `GzipStream` to write 100 bytes, but it's only able to write 50 bytes without blocking, it would return 50 and I'd know to ask it to write only the remaining 50 bytes next time around.

**Comment by benaadams** [comment]
> the Stream.Read() abstraction does return an int, and may read less than what was requested. This asymmetry is odd and not really necessary.

That isn't particularly related to non-blocking; more due to the size of the given read buffer potentially being larger than the read and particularly since a return of `0` is end of stream.

If you look at the [stream to stream copy method](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/IO/Stream.cs#L217-L225) which uses a [default buffer size of 81kB](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/IO/Stream.cs#L41-L44) generally read will return less that 81kB and when it returns 0 it has finished.

If it didn't return how much it read; then you couldn't read a 2kB file with a 81kB buffer as it wouldn't have a way of signalling how much it had read.

**Comment by roji** [comment]
@benaadams,

> > the Stream.Read() abstraction does return an int, and may read less than what was requested. This asymmetry is odd and not really necessary.
> 
> That isn't particularly related to non-blocking; more due to the size of the given read buffer potentially being larger than the read and particularly since a return of 0 is end of stream.

The `Stream.Read()` documentation states that the number returned `can be less than the number of bytes requested if that many bytes are not currently available`. When reading from a `NetworkStream` this is of course very important - if you want to actually read 100 bytes you need to place `Read()` in a loop. In that sense, as long as there are _some_ bytes available for reading, `Read()` is already "non-blocking". Of course when there are 0 bytes available, `Read()` will block unless O_NONBLOCK has been specified on the socket.

So again, this behavior is already available when reading streams, but is curiously absent when writing...

Note: I realize that changing `Stream.Write()` isn't possible, I'd just like to make sure that any new I/O abstraction not make the same mistake (assuming it indeed makes sense to add this).

**Comment by benaadams** [comment]
To continue the documentation

>  or zero (0) if the end of the stream has been reached.

So a non-blocking read of 0 is not available as a 0 read means close.

**Comment by roji** [comment]
> So a non-blocking read of 0 is not available as a 0 read means close.

IIRC, if the socket is set to non-blocking mode and a read would block, `NetworkStream.Read()` throws a SocketException with `SocketError.WouldBlock` (am not next to a computer to confirm). This allows you to distinguish between close and "no bytes available".

**Comment by benaadams** [comment]
And throwing an exception is very very slow... Anyway... bit of a divergence.

Let's generalise, there are 3 forms of IO: blocking, polling and callback

You would like to make sure polling is catered for?

**Comment by benaadams** [comment]
And as an aside you can do non-blocking with .Net Tasks; you don't have to await/async them or .ContinueWith, just keep  querying them and checking their state to see if they are done.

**Comment by roji** [comment]
@benaadams I agree it's unfortunate that .NET exposes EWOULDBLOCK as an exception, but that's a different discussion as you say.

Regarding doing non-blocking with .NET Tasks, this again blurs the line between non-blocking and async. Non-blocking is about reading/writing whatever is possible, and continuing on the same thread - whereas with async the continuation (or callback) runs on another thread. In some application designs this transition to another thread is inappropriate. Non-blocking really is a different form of I/O as you specified above.

Finally yes, your generalization of I/O to 3 forms - blocking, polling (i.e. non-blocking) and callback (i.e. async) - seems right to me. The first and third forms seems to be fully supported by .NET's Stream abstraction, while the second one doesn't... Unless there's some fundamental reason that doesn't make sense.

**Comment by benaadams** [comment]
I would suggest in channels the "what have you got currently" for read is supported; and non-blocking for write makes no sense (as it is just ownership transfer) - though @davidfowl could confirm.

(Well accept for back pressure... )

**Comment by davidfowl** [comment]
Yea, I'm not 100% sure what API a non blocking write would have. What would you expect? Are you looking for an abstraction that exposes the underlying readiness model of poll/epoll/kqueue?

**Comment by roji** [comment]
Well, I'd start with the very basics - poll/epoll/kqueue are facilities for polling on multiple sockets at the same time, whereas my concern here is simply to expose the basic possibility of attempting to write to a (single) socket without ever blocking. 

I'd expect .NET to support the basic model provided by the [Linux write system call](http://man7.org/linux/man-pages/man2/write.2.html): make write return the number of bytes written, which could be less that the number requested if the socket has been set to non-blocking and a write would block. If no bytes at all are available, raise an EWOULDBLOCK just like read does. It's just a matter of exposing this basic, standard network I/O operation in .NET - no fancy additional abstractions or anything.

Beyond that, an efficient .NET abstraction over poll/epoll/kqueue would of course be incredibly useful - but it seems like a separate issue that probably could be dealt with later (whereas if the above isn't dealt with right at the start it may be impossible to add it later, see `Stream.Write()`).

**Comment by roji** [comment]
I'll try to find some time in the coming days to better understand exactly what the new channels API looks like, at which point I'll probably be able to make more useful suggestions.

**Comment by benaadams** [comment]
The non-blocking says "can't copy to kernel buffer, is full".

In this model you aren't copying you are transferring the ownership of the data (so the buffers are a big as you want them to be in user mode, with no copies other than implementation details); however you wouldn't want them to grow unbounded - so an equivalent might be "hasBackpressure" type flag you could check e.g. you are adding much faster than its being processed?

**Comment by davidfowl** [comment]
@roji did you have a chance to play with it?

**Comment by roji** [comment]
@davidfowl sorry, not yet, have been too busy with other things... I do promise to give it a try as soon as I can, I'm very interested in what you're doing here.

**Comment by davidfowl** [comment]
np

**Comment by davidfowl** [comment]
This post might help http://blog.marcgravell.com/2016/09/channelling-my-inner-geek.html

**Comment by davidfowl** [comment]
After thinking about this a bit, a non blocking API would look like TryWrite and TryRead. They would attempt to do the operation synchronously and return false if they didn't succeed.

**Comment by roji** [comment]
@davidfowl that sounds like a good API for exposing non-blocking I/O. Unfortunately in .NET non-blocking I/O usually involves catching an exception (WouldBlock), which is annoying for first-time exceptions etc.
