### ISSUE TITLE
Do we need a common transport API

### ISSUE THREAD

**Issue by mgravell** [davidfowl/Channels#58]
libuv, managed sockets, RIO, files - heck,  lot of things channel related - have very similar features. At the moment it is hard to talk about a generalized provider. Do we need one? Spitballing:

```
interface IChannel : IDisposable {
    IReadableChannel Input {get; }
    IWritableChannel Output {get; }
}
```

That provides IO and lifetime management.

Is this useful? Or is this an artificial similarity brought about that we have multiple network related providers?

**Comment by mgravell** [comment]
Obvious comment is obvious, but this would apply both to final implementation code (the actual server or client software), and to pipes like SSL, gzip, deflate - allowing them all just to work against (and re-expose, in the case of pipes) a single common interface.

**Comment by davidfowl** [comment]
This is good. I was wondering if `IChannel` should implement both channels or have channels. I like this design. Lets try it.

**Comment by davidfowl** [comment]
Done
