### ISSUE TITLE
[Question] Is this related to System.Threading.Tasks.Channels 

### ISSUE THREAD

**Issue by shaggygi** [davidfowl/Channels#60]
Just wondering if this project is similar to the one in CoreFxLabs?

https://github.com/dotnet/corefxlab/tree/master/src/System.Threading.Tasks.Channels

**Comment by benaadams** [comment]
corefx labs one is a higher level operating on object streams `T` this is a lower level operating on raw data `byte[]` streams; e.g reading/writing from network, file, pipe etc; while abstracting the transport (socket, libuv, RIO, file, pipe etc)

See: https://github.com/davidfowl/Channels/issues/11

**Comment by shaggygi** [comment]
Thanks @benaadams for pointing this out.
