### ISSUE TITLE
Should readable buffers return `ReadOnlySpan<byte>`?

### ISSUE THREAD

**Issue by mgravell** [davidfowl/Channels#69]
Currently returns `Span<byte>`; but intent is only to read

Minor caveat / discussion point; the web-socket code _does_ intentionally mutate the state of the input, when applying the xor mask. But since we're doing that against the unsafe pointer _anyway_, all bets are off.

Additional question for corefxlabs; should there be an additional operator?

```
public static explicit operator Span<T>(ReadOnlySpan<T> slice);
```

Since the caller can already do this indirectly if they want, it may be prudent to at least acknowledge this (and make it more convenient).

Note  that  a number of the APIs could talk `ReadOnlySpan<byte>` rather than `Span<byte>` without consequence.

**Comment by benaadams** [comment]
`Span<T>(ReadOnlySpan<T> slice)` should only exist if it copies; else array returning methods (e.g. lookup tables) will always have to defensively copy to guard against mutation.

The fact you can do it via unsafe is ok; as you can mutate a string via unsafe and also mutate a static readonly via dodgy reflection - it will also break stuff - but that's unsafe :grin: 

The conversion without copy would allow you to violate the readonly and break stuff without going unsafe which would be bad...

**Comment by mgravell** [comment]
That's fair

**Comment by mgravell** [comment]
`Span<T> ReadOnlySpan<T>.UnsafeToMutableSpan(void* dummyProveToMeThatYouAreUnsafe)` :)

**Comment by benaadams** [comment]
As an example I'd hope future apis could return `ReadOnlySpan<T>` rather than doing this to guard against Array's mutability https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/IO/Path.cs#L287-L295

**Comment by mgravell** [comment]
Until they changed the JIT, you used to be able to use reflection to change the value of `string.Empty`; that's always fun for a giggle....

**Comment by davidfowl** [comment]
Yea I actually almost did this but then decided against it when I saw I actually also edit in place (though it should be an unsafe operation).
