### ISSUE TITLE
Consider making the IWritableChannel awaitable

### ISSUE THREAD

**Issue by davidfowl** [davidfowl/Channels#7]
Instead of having EndWriteAsync return a `Task`

**Comment by marianogenovese** [comment]
Hi! David this project seems very interesting from the point of view of the programming structure to create new channels and manage connections. I am implementing an SSL server for streaming, I'm trying to implement channels like test project. I have a question, if I implement a channel for writing if the client has been disconnected, how this case is controlled to destroy the connection or stop delivering data to the client? in the sample project you do this with the read channel in the loop reading (HTTPConnection class) but in my case, not necessarily the client can send something to the beginning of the connection, the client may connect and start receiving server information.

Thanks.

**Comment by davidfowl** [comment]
@marianogenovese  This is a gap in the API that I'm addressing right now. Thanks for the feedback! Keep it coming

**Comment by davidfowl** [comment]
This should be addressed with the latest changes. When the channel you're writing to fails, it'll mark the task returned from WriteAsync will fail. I'll turn this into an awaitable channel at some point

**Comment by marianogenovese** [comment]
Ok, i have update my test with last sources and fails when client is disconnected.

**Comment by marianogenovese** [comment]
Any plans to implements SSL over Libuv?

**Comment by davidfowl** [comment]
The TLS/SSL channel https://github.com/davidfowl/Channels/issues/3 will just be a channel pair that can sit on any other channel (like SSL Stream works today). That means you'll be able to do SSL over libuv or anything else really. 

I just need to start 😄

**Comment by marianogenovese** [comment]
This means that i can implement tls/ssl over libuv making a libuv stream? and this pass to sslstream class constructor or i'm wrong?

**Comment by davidfowl** [comment]
@marianogenovese Did you ever figure this out? I added a bunch of helpers that will make this easier.
