### ISSUE TITLE
Writing utf8 string fails for large strings

### ISSUE THREAD

**Issue by mgravell** [davidfowl/Channels#70]
See: https://github.com/mgravell/channels/tree/failing-test-large-data, in particular [`WriteLargeDataTextUtf8`](https://github.com/mgravell/Channels/blob/failing-test-large-data/test/Channels.Tests/WritableBufferFacts.cs#L84)

Wanted to check expectation here before trying to jump in with any fix

**Comment by mgravell** [comment]
It looks like the biggest blocker here is lack of availability for  pointer-based `Encoder` APIs in core-CLR; can _just about_ do it with `Encoding`, but need to default to pathologically pessimistic, since the `Convert` API doesn't allow a very flexible "do as much as you can, and allow me to pick up in a moment" API (which is what `Encoder` is meant to allow).

What we need to do is loop, encode as much as we can into the `.Memory`, and use `Ensure` etc again as necessary. I've fixed `WriteAsciiString` in the branch.

**Comment by mgravell** [comment]
I've updated the branch with the pathological scenario `WriteUtf8String` implementation; it might actually be _more efficient_ than the  old code, as we no longer require to pre-compute the length.

**Comment by davidfowl** [comment]
I also noticed this when looking at the code last night.
