### ISSUE TITLE
API suggestion re Ensure

### ISSUE THREAD

**Issue by mgravell** [davidfowl/Channels#72]
`Ensure` doesn't do what it claims; IMO, if it can't allocate what is requested into a single block, it should fail with an exception (typically caused by asking for more than `BlockSize`)

Additional API suggestion: a `int TryEnsure(int minBytes, int maxBytes)`:

(could also just  be called `Ensure`)
- throws if `minBytes > BlockSize` - can never satisfy that
- if `>= maxBytes`  left on the current block, returns `maxBytes` - it all fits on the block 
- if `>=minBytes` and `< maxBytes` left on the current block , returns whatever space is left on the current block 
- else jumps to a new block and returns `Min(maxBytes, BlockSize)`

The `return` value is the number of bytes that you are allowed to work with.

This would allow me to try to fill up blocks during encoding.

**Comment by mgravell** [comment]
Note the second part of this is obviated by pattern clarification (example: https://github.com/davidfowl/Channels/commit/96625759a79263a3577d9f658eadfd4cc2b25c1c); however, I still think that the "ensure doesn't actually ensure" is a problem that is going to byte people

**Comment by davidfowl** [comment]
> however, I still think that the "ensure doesn't actually ensure" is a problem that is going to byte people

Agreed!

> byte people
> 😄
