### ISSUE TITLE
Need a new enumerator pattern

### ISSUE THREAD

**Issue by jaredpar** [davidfowl/Channels#73]
Noticed that several of the types have the following pattern:

``` csharp
class Enumerator : IEnumerable<Span<byte>>
```

This isn't going to work when we get proper validation of `Span<T>` in the compiler.  One of the restrictions, due to the stack only nature, is that `Span<T>` can't appear as a generic argument.  

May have to consider a slight alteration like:

``` csharp
interface ISpanEnumerable<T>
{
  Span<T> Current { get; }
}
```

**Comment by mgravell** [comment]
Frankly I don't think it matters that these types implement that interface. It would only add overhead anyway! The compiler duck typing pattern is fine.

**Comment by benaadams** [comment]
`IBatchEnumerable`?

``` csharp
public interface IBatchEnumerable<T, TEnumerator>
{
    TEnumerator StartBatchEnumeration { get; } 
    bool TryGetNext(ref TEnumerator enumerator, out Span<T> items);
}

public interface IAsyncBatchEnumerable<T, TEnumerator>
{
    TEnumerator StartBatchAsyncEnumeration { get; } 
    Task<bool> WhenNextAsync(ref TEnumerator enumerator);
    bool TryGetNext(ref TEnumerator enumerator, out Span<T> items);
}
```

Type in `foreach` can be inferred by the `Span<T>` return type as it can't be returned by a normal `IEnumerable` due to the aforementioned generic argument restriction.

**Comment by davidfowl** [comment]
I'm going to remove the `IEnumerable<T>` methods. Question though, would this work @jaredpar :

``` C#
var spans = new List<Span<byte>>();
foreach (var s in helloBuffer)
{
    spans.Add(s);
}
```

**Comment by KrzysztofCwalina** [comment]
@mgravell, if we want reusable routines that operate on multiple Spans, we need an abstraction for a sequence of spans. 
Here is an example of such reusable routine: https://github.com/dotnet/corefxlab/blob/master/src/System.Buffers.Experimental/System/Buffers/MultispanExtensions.cs#L12

**Comment by jaredpar** [comment]
@davidfowl no.  The `Span<T>` type cannot be used as a generic argument.  That restriction applies to type definitions and type instances.  

A good rule of thumb for whether it is okay for `Span<T>` to do something is essentially to ask if `T*` would be legal in the same position (ignoring the need for `unsafe` context).  They have virtually the same restrictions because really `Span<T>` can be simply wrapping a `T*`.

**Comment by davidfowl** [comment]
@KrzysztofCwalina looks like that won't work then. I think this limitation is too much.

**Comment by KrzysztofCwalina** [comment]
There is no fundamental issue with span being a generic argument as long as the argument is in a contravariant position. In the worst case we will do something along the lines of ISpanEnumerable (as Jared suggested).

**Comment by jaredpar** [comment]
It's not necessarily an issue of co / contra variance.  The more pressing issue is that you have to convey the stack only (or really pointer like) nature of the type through the generics.  The stack constraint has to flow through all paths. 

Consider this example where `T` is in a covariant position and is used in a stack only nature:

``` csharp
interface IExample<out T> {
  T Prop { get; }
}

struct Impl : IExample<Span<byte>> { 
  Span<byte> Prop { get; }

  Impl(Span<byte> arg) {
    Prop = arg;
  }
}
```

This alone is fine and safe.  But it's not enough because I can still put a `Span<byte>` in the heap by doing the following:

``` csharp
void M<U, V>(U arg) where U : struct, IExample<V>
{
  object o = arg; 
}

M<Impl, byte>(new Impl(GetSpan()));  // Just boxed a Span<byte>
```

In order to make `Span<T>` safe for generics and possible to implement interfaces there need to be a couple of features:
- Need a new constraint on type parameters specifying instances of the type parameter will never be put onto the heap.  For example `where T : noheap` 
- Need a new type of conversion in the language such that types like `Span<T>` can **only** convert to implemented interfaces when the target is a generic type parameter that has the `noheap` constraint.  

If that last bit is confusing (it was confusing to type) then here's an example to help:

``` csharp
Impl i = new Impl(GetSpan());
IExample<Span<byte>> e = i;  // Error: tried to box a stack only type 

void G<U, V>(U arg) where U: noheap, struct, IExample<V> 
{
   object o = arg; // Error: violation of noheap
   IExample<V> e = arg; // Error: violation of noheap 
   Console.WriteLine(arg.Prop.Length);  // Okay:
}

G(i); // Okay
```

**Comment by jaredpar** [comment]
To be clear I'm not suggesting we do this.  Only that this is the lengths you need to go to if you want to make a stack only version of `Span<T>` safe for generics.

**Comment by KrzysztofCwalina** [comment]
Is Impl a stack-only type too? In this case, passing it to G<U> should fail as U is not in a contravariant position.

**Comment by jaredpar** [comment]
@KrzysztofCwalina yes `Impl` is a stack only type as well as it has a field which is stack only. 

> In this case, passing it to G should fail as U is not in a contravariant position.

This is perfectly fine.  The co / contra varaint checks are enforced when constructing types.  All such types are properly constructed here.  It's not checked when instantiating methods.  

Here is a gist that demonstrates this validates: https://gist.github.com/jaredpar/b28483ec51c1ef74076f64b94d272115

Again though, co / contra aren't really a good way of trying to enforce stack only here.  It has some intersection of restrictions but much more is needed to properly enforce the necessary restrictions.

**Comment by KrzysztofCwalina** [comment]
I agree that more needs to be done. I was just saying that fundamentally there is nothing wrong with the interface, nor we need new constraints. We could just add more restrictive checks for stack-only types.

**Comment by jaredpar** [comment]
>  nor we need new constraints. 

That's only true if you don't want stack only types to participate in generics.  If you want stack only types to participate in generics then a new constraint / annotation is required.

**Comment by VSadov** [comment]
Just to mention - compiler already have a notion of ref-like (aka stack-only) types. That is for the small existing set including things like ArgIterator, TypedReference, etc ...

We already have a way of enforcing that types in that set are never a field, element type, boxed, generic argument and so on.

As a simple solution Span<T> would be added to the set.
Whether that would be too limiting is another question.

**Comment by KrzysztofCwalina** [comment]
meanwhile we can do the following (as Jared suggested):

``` csharp
interface ISpanEnumerable<T>
{
  Span<T> Current { get; }
}
```
