### ISSUE TITLE
What is the behavior when you close either the input or output but expect the otherside to continue?

### ISSUE THREAD

**Issue by Drawaes** [davidfowl/Channels#83]
I have the scenario of
Create Channel, that creates a TCP socket. Then i start reading. Messages are sent to the writer. When the application wants to shutdown it sends a shutdown message to the otherside and then does

channel.Output.Complete()

But I would expect that the channel.Input will continue to receive data until the "session compeleted" message is received from the otherside at which point I would call

channel.Input.Complete()

Will this work, or will the first Complete() cause the socket to be closed? If so I will need to do some synchronization in my client code.

**Comment by Drawaes** [comment]
My proposal would be.
Calling [Input/Output].Complete() does not close the socket but causes back pressure on the receive (or send)
If both are called then the socket is closed.
and a new method Channel.Complete() that basically calls complete() on both of them.

**Comment by mgravell** [comment]
Agree that what you suggest is my expectation as a consumer. To compare with socket: you can happily shut down either input or output and keep using the other.

**Comment by Drawaes** [comment]
To add weight to this (although I think it is going ahead) the AMQP spec actually mentions this exact scenario (From AMQP 1.0)

> Prior to closing a Connection, each peer MUST write a close frame with a code indicating the reason
> for closing. This frame MUST be the last thing ever written onto a Connection. After writing this
> frame the peer SHOULD continue to read from the Connection until it receives the partner’s close
> frame

**Comment by mgravell** [comment]
That doesn't mention anything about formally closing the socket. It just says it must be the last thing sent.

**Comment by Drawaes** [comment]
No exactly. So the send side is "completed" and therefore any part of the application trying to do so should be told that. The socket shouldn't be closed until the close is received (and any other messages in flight). Which is exactly the point, "completing writing" doesn't mean that you shouldn't be forced to have reading completed. And any write in this case should feel backpressure.

**Comment by Drawaes** [comment]
I think this is fixed now and can be closed?
