### ISSUE TITLE
Being able to write the at the start of a message after committing bytes

### ISSUE THREAD

**Issue by Drawaes** [davidfowl/Channels#84]
It is common for many formats to have a "message length" near the start of the message. 

Currently you would have to "know" or calculate the size of the message you expect to write, or you would need to write it in another buffer and then measure before copying (making the zero copy idea a bust).

Today I am doing this by

``` c#
buffer.Ensure(4);
var header = buffer.Memory.Slice(0,4);
buffer.Memory.Write(0);
buffer.CommitBytes(4);


//Write message out counting committed bytes

header.Write(messageLength);

await buffer.FlushAsync();
```

But this is a bit messy, so either put a method as @mgravell suggested 

buffer.Reserve(4);

or I can write a "MessageWriter (with maybe a big endian/little endian style)" struct that will do this for you, where you could denote the byte number that the "Size" started at

**Comment by mgravell** [comment]
Crossref: https://github.com/davidfowl/Channels/pull/86
