### ISSUE TITLE
Race condition between flush and commit bytes

### ISSUE THREAD

**Issue by Drawaes** [davidfowl/Channels#88]
[Sample Code](https://github.com/Drawaes/ChannelsTesting)

Fails on managed sockets but works with libuv (only the server is changing) #

**Comment by mgravell** [comment]
Consider me assigned

**Comment by Drawaes** [comment]
[Update to the tail ref](https://github.com/davidfowl/Channels/blob/master/src/Channels/Channel.cs#L97-L116)

The tail reference updates to the new alloc and the new alloc can commit bytes, before the last "flush" has been read by the writer, causing unflushed bytes to be sent to the consumer before the producer has commited to them

[Where the consumer is given the current available bytes](https://github.com/davidfowl/Channels/blob/master/src/Channels/Channel.cs#L179-L187)

**Comment by mgravell** [comment]
Are you calling flush multiple times on the same buffer?

**Comment by Drawaes** [comment]
no. 

``` C#
for(int i = 0; i < totalMessages;i++)
            {
                var buff = channel.Output.Alloc(100);
                buff.Ensure(2);
                buff.Memory.Write(empty);
                buff.CommitBytes(2);

                buff.Ensure(8);
                buff.Memory.Write(data2);
                buff.CommitBytes(8);
                channel.Output.Alloc(10);

                await buff.FlushAsync();
            }

            System.Threading.Thread.Sleep(5000);

            var buff2 = channel.Output.Alloc(100);
            buff2.Ensure(2);
            buff2.Memory.Write(empty);
            buff2.CommitBytes(2);

            buff2.Ensure(8);
            buff2.Memory.Write(data2);
            buff2.CommitBytes(8);
```

**Comment by Drawaes** [comment]
that doesnt send the end bytes take out the sleep and it does

**Comment by benaadams** [comment]
Alloc is changing the `_tail` (when is enough in current block) but it shouldn't be; only Append should be changing the `_tail`

**Comment by benaadams** [comment]
Use `Advance` not `CommitBytes`
