### ISSUE TITLE
Would be useful to have a "Bytes Written" on the WritableBuffer

### ISSUE THREAD

**Issue by Drawaes** [davidfowl/Channels#92]
This would mean if you are writing a "content" length header you could do

var headerCursor = buffer.Memory;
buffer.Write(0);
message.Write(buffer)
headerCursor.Write<uint>( buffer.BytesWritten);
buffer.FlushAsync();

Otherwise you need to track all the writes all the way down the stack to figure out the length or do
AsReadableBuffer().Len

**Comment by mgravell** [comment]
in real world usage, I think what you need here is actually subtraction on cursors, i.e.

```
var pos = /* position before the payload */
WritePayload(...)
var len = buffer.End - pos; // number of bytes
prefix.Write(len);
```

Things that I think are fine:

```
operator ReadCursor +(ReadCursor, int);
operator int -(ReadCursor, ReadCursor);
```

**Comment by Drawaes** [comment]
#93 Is all that is needed for now, until cursors have operators :)

**Comment by mgravell** [comment]
well, you could always write them... the trick is that in **both** cases you want to start with the earlier one (so the second operator in `-`), and look at each segment in turn walking forward via `.Next`

**Comment by Drawaes** [comment]
Maybe, but might the cursor operators mean something else to most people? 

Eg Cursor + 2 I would (and tried at the start) a cursor that is 2 bytes forward

The cursor - cursor is valid though

**Comment by davidfowl** [comment]
Subtraction on cursors require a back pointer in the linked list. Not sure about that yet.

**Comment by Drawaes** [comment]
Agreed. For now the primary issue is complete
